# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mymodule', [dirname(__file__)])
        except ImportError:
            import _mymodule
            return _mymodule
        if fp is not None:
            try:
                _mod = imp.load_module('_mymodule', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mymodule = swig_import_helper()
    del swig_import_helper
else:
    import _mymodule
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mymodule.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _mymodule.SwigPyIterator_value(self)
    def incr(self, n = 1): return _mymodule.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _mymodule.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _mymodule.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _mymodule.SwigPyIterator_equal(self, *args)
    def copy(self): return _mymodule.SwigPyIterator_copy(self)
    def next(self): return _mymodule.SwigPyIterator_next(self)
    def __next__(self): return _mymodule.SwigPyIterator___next__(self)
    def previous(self): return _mymodule.SwigPyIterator_previous(self)
    def advance(self, *args): return _mymodule.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _mymodule.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _mymodule.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _mymodule.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _mymodule.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _mymodule.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _mymodule.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _mymodule.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class BinaryBzet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinaryBzet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BinaryBzet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _mymodule.new_BinaryBzet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mymodule.delete_BinaryBzet
    __del__ = lambda self : None;
    def getBzetString(self): return _mymodule.BinaryBzet_getBzetString(self)
    def getBzetBinaryString(self): return _mymodule.BinaryBzet_getBzetBinaryString(self)
    def getBzetPretty(self): return _mymodule.BinaryBzet_getBzetPretty(self)
    def getCharFromBzet(self, *args): return _mymodule.BinaryBzet_getCharFromBzet(self, *args)
    def isTAWatching(self): return _mymodule.BinaryBzet_isTAWatching(self)
    def __and__(self, *args): return _mymodule.BinaryBzet___and__(self, *args)
    def __or__(self, *args): return _mymodule.BinaryBzet___or__(self, *args)
    def __xor__(self, *args): return _mymodule.BinaryBzet___xor__(self, *args)
    def __eq__(self, *args): return _mymodule.BinaryBzet___eq__(self, *args)
    def __invert__(self): return _mymodule.BinaryBzet___invert__(self)
    def FALSE(self, *args): return _mymodule.BinaryBzet_FALSE(self, *args)
    def AND(self, *args): return _mymodule.BinaryBzet_AND(self, *args)
    def NonImplication(self, *args): return _mymodule.BinaryBzet_NonImplication(self, *args)
    def A(self, *args): return _mymodule.BinaryBzet_A(self, *args)
    def ConverseNonImplication(self, *args): return _mymodule.BinaryBzet_ConverseNonImplication(self, *args)
    def B(self, *args): return _mymodule.BinaryBzet_B(self, *args)
    def XOR(self, *args): return _mymodule.BinaryBzet_XOR(self, *args)
    def OR(self, *args): return _mymodule.BinaryBzet_OR(self, *args)
    def NOR(self, *args): return _mymodule.BinaryBzet_NOR(self, *args)
    def EQ(self, *args): return _mymodule.BinaryBzet_EQ(self, *args)
    def NotB(self, *args): return _mymodule.BinaryBzet_NotB(self, *args)
    def ConverseImplication(self, *args): return _mymodule.BinaryBzet_ConverseImplication(self, *args)
    def NotA(self, *args): return _mymodule.BinaryBzet_NotA(self, *args)
    def Implication(self, *args): return _mymodule.BinaryBzet_Implication(self, *args)
    def NAND(self, *args): return _mymodule.BinaryBzet_NAND(self, *args)
    def TRUE(self, *args): return _mymodule.BinaryBzet_TRUE(self, *args)
    def compare(self, *args): return _mymodule.BinaryBzet_compare(self, *args)
    def leftShift(self, *args): return _mymodule.BinaryBzet_leftShift(self, *args)
    def rightShift(self, *args): return _mymodule.BinaryBzet_rightShift(self, *args)
    def slice(self, *args): return _mymodule.BinaryBzet_slice(self, *args)
    def getDepth(self): return _mymodule.BinaryBzet_getDepth(self)
    def size(self): return _mymodule.BinaryBzet_size(self)
    def set(self, *args): return _mymodule.BinaryBzet_set(self, *args)
    def unset(self, *args): return _mymodule.BinaryBzet_unset(self, *args)
    def flip(self, *args): return _mymodule.BinaryBzet_flip(self, *args)
    def clean(self): return _mymodule.BinaryBzet_clean(self)
    def countBits(self): return _mymodule.BinaryBzet_countBits(self)
    def getFirstBit(self): return _mymodule.BinaryBzet_getFirstBit(self)
    def getLastBit(self): return _mymodule.BinaryBzet_getLastBit(self)
    def bitList(self): return _mymodule.BinaryBzet_bitList(self)
    def AlignCompare(self, *args): return _mymodule.BinaryBzet_AlignCompare(self, *args)
    __swig_getmethods__["getLastBitTest"] = lambda x: _mymodule.BinaryBzet_getLastBitTest
    if _newclass:getLastBitTest = staticmethod(_mymodule.BinaryBzet_getLastBitTest)
    def flipTEST(self): return _mymodule.BinaryBzet_flipTEST(self)
    def setTEST(self): return _mymodule.BinaryBzet_setTEST(self)
    def expandTEST(self): return _mymodule.BinaryBzet_expandTEST(self)
    def bzetWalkTEST(self): return _mymodule.BinaryBzet_bzetWalkTEST(self)
    def bitSetCollapseTEST(self): return _mymodule.BinaryBzet_bitSetCollapseTEST(self)
    __swig_getmethods__["testShift"] = lambda x: _mymodule.BinaryBzet_testShift
    if _newclass:testShift = staticmethod(_mymodule.BinaryBzet_testShift)
    def align(self, *args): return _mymodule.BinaryBzet_align(self, *args)
    def bsCopy(self, *args): return _mymodule.BinaryBzet_bsCopy(self, *args)
    def bsNeg(self, *args): return _mymodule.BinaryBzet_bsNeg(self, *args)
    def bzetWalk(self, *args): return _mymodule.BinaryBzet_bzetWalk(self, *args)
    def traversalSkeleton(self, *args): return _mymodule.BinaryBzet_traversalSkeleton(self, *args)
    def doDataOp(self, *args): return _mymodule.BinaryBzet_doDataOp(self, *args)
    def binaryOp(self, *args): return _mymodule.BinaryBzet_binaryOp(self, *args)
BinaryBzet_swigregister = _mymodule.BinaryBzet_swigregister
BinaryBzet_swigregister(BinaryBzet)
cvar = _mymodule.cvar
c_u32_max = cvar.c_u32_max
c_i32_min = cvar.c_i32_min

def BinaryBzet_getLastBitTest():
  return _mymodule.BinaryBzet_getLastBitTest()
BinaryBzet_getLastBitTest = _mymodule.BinaryBzet_getLastBitTest

def BinaryBzet_testShift():
  return _mymodule.BinaryBzet_testShift()
BinaryBzet_testShift = _mymodule.BinaryBzet_testShift

# This file is compatible with both classic and new-style classes.


